### ISSUE TITLE
Mozart dataset down?

### ISSUE THREAD

**Issue by f90** [richardassar/SampleRNN_torch#10]
Hey,

the Mozart dataset file at
https://archive.org/compress/MozartCompleteWorksBrilliant170CD/formats=OGG%20VORBIS&file=/MozartCompleteWorksBrilliant170CD.zip
seems to be not available anymore. Can you rehost it somewhere else or find a working link for this please? I am trying to use this for my own experiments.

**Comment by richardassar** [comment]
I didn't retain a copy of this and can't find an alternative link so you'll have to source your own material.
