### ISSUE TITLE
running fast_sample

### ISSUE THREAD

**Issue by kylemcdonald** [richardassar/SampleRNN_torch#5]
thanks for this port. i've tried the original and wanted to compare in terms of performance. i successfully got the training running (~20 hours for 33 minibatches on a K80 -- which i think is one epoch? i couldn't find the epoch indication in the output and haven't dug through the code yet).

it looks like `th train.lua -generate_samples` will take ~1 hour to generate 5x 20 second samples. that's or about 36 seconds to generate 1 second of audio. does that sound right?

i want to get fast_sample running but it gives me errors. first it said that it couldn't find `LinearWeightNorm`. i made sure that i had the most recent `nn` installed. that didn't help, but when i changed the line to `require 'nn. LinearWeightNorm'` then it worked.

now it is giving me errors about not finding `SeqGRU_WN`, `SeqLSTM_WN` and `SeqLSTMP_WN`. is there something else i need to do with these files or should lua be able to identify them since they're adjacent to the script?

edit: that should be 5x 55 second samples since this is at 16kHz instead of 44.1kHz. making it closer to 13 seconds to generate 1 second of audio.

**Comment by robinsloan** [comment]
After pulling the latest changes, I encountered the same problem, and solved it with the following steps:

* Delete `require 'LinearWeightNorm'` entirely (because it's included in the latest `nn`)
* Delete `require 'SeqLSTMP_WN'` as well (which appears to be left over from a previous commit)

It's working for me now! I get 10 seconds of audio in ~120 seconds on a Titan X.

**Comment by richardassar** [comment]
Thanks Robin. I've made the changes in https://github.com/richardassar/SampleRNN_torch/commit/a5af976cf618a07cebd6965705190164be1f57fe

Closing for now but if @kylemcdonald you still experience issues then let me know, thanks.
