### ISSUE TITLE
The condition to stop

### ISSUE THREAD

**Issue by hello1tiger** [richardassar/SampleRNN_torch#9]
The parameter 'max_epoch' was set to 'math.huge', as I did not change it before training, would it be in training all the time? Are there any other terminating conditions? If not, how could I stop it?

**Comment by richardassar** [comment]
CTRL+C

**Comment by richardassar** [comment]
Also, this is a trivial operation - killing a processes.

You're looking into deep learning but you don't know how to kill a process?

There is no issue with my code and so this is improper use of github issues, you could have googled for solutions to your problem first. Please try to learn what is appropriate.
